### PR TITLE
fix #49 with a unified approach/function

### LINKED ISSUE #49: Different code depending on fortify method?
The 'make nodes data of identical dimensions to edges data' code differs:

https://github.com/briatte/ggnetwork/blob/0bba28bccc7df6fa9c9d9ac33710f89470b2bdb8/R/fortify-igraph.R#L101-L103

https://github.com/briatte/ggnetwork/blob/0bba28bccc7df6fa9c9d9ac33710f89470b2bdb8/R/fortify-network.R#L179-L183

… and I have no idea why.

The code in `fortify.network` fails to pass tests if copy-pasted into `fortify.igraph`.

### PR DESCRIPTION
**Pull request by mcanouil**
I created a new internal function `format_fortify` to homogenise the two `fortify` which were basically doing the exact same thing but relying on two different packages.
Amongs other things, this fix the issue #49 and will make things easier to maintain the fortify function (only one place to look for any modification)

### CODE REVIEW

File: R/utilities.R [hunk 1]
```diff
@@ -80,3 +80,165 @@ NULL
...
+
+  # rescale coordinates
+  if (scale) {
+    nodes$x <- scale_safely(nodes$x)
+    nodes$y <- scale_safely(nodes$y)
+  }
+
+  # import vertex attributes
+  if (length(.lva(model)) > 0) {
+    nodes <- cbind.data.frame(
```
Comment (briatte) [inline R/utilities.R]: Are you sure this method does not recreate issue #54?

File: R/fortify-network.R [hunk 2]
```diff
@@ -136,88 +116,18 @@ fortify.network <- function(
...
-  }
+  format_fortify(
+    model = model,
+    nodes = nodes,
+    weights = weights,
+    arrow.gap = arrow.gap,
+    by = by,
+    scale = scale,
+    stringsAsFactors = stringsAsFactors,
+    .lva = network::list.vertex.attributes,
```
Comment (briatte) [inline R/fortify-network.R]: That's super smart, although I'll probably rename the functions to more explicit handles.

File: R/fortify-igraph.R [hunk 3]
```diff
@@ -1,29 +1,13 @@
...
-#'   nodes of the network will appear in all facets, at the same coordinates.
-#'   Defaults to \code{NULL} (no faceting).
-#' @param scale whether to (re)scale the layout coordinates. Defaults to
-#'   \code{TRUE}, but should be set to \code{FALSE} if \code{layout} contains
-#'   meaningful spatial coordinates, such as latitude and longitude.
-#' @param stringsAsFactors whether vertex and edge attributes should be
-#'   converted to factors if they are of class \code{character}. Defaults to
-#'   the value of \code{getOption("stringsAsFactors")}, which is \code{TRUE} by
-#'   default: see \code{\link[base]{data.frame}}.
+#' @inheritParams format_fortify
```
Comment (briatte) [inline R/fortify-igraph.R]: Was working on something similar offline, but your code is much cleaner than what I came up with!

**Comment by briatte** [comment]
I believe this will also simplify tests a bit.

I have only one hesitation about the `cbind`/`sapply` method, given issue #59.

File: R/utilities.R (hunk 1 above)
Comment (mcanouil) [reply R/utilities.R]: yes, at least all tests were successful (travis/appveyor and testthat).
Basically the result from the `sapply(..., SIMPLIFY = FALSE)` is a named list, so using `cbind.data.frame` recreates the data.frame.

File: R/fortify-network.R (hunk 2 above)
Comment (mcanouil) [reply R/fortify-network.R]: I pushed a commit with "big names".

File: R/fortify-igraph.R (hunk 3 above)
Comment (mcanouil) [reply R/fortify-igraph.R]: Thanks^^

File: R/utilities.R (hunk 1 above)
Comment (briatte) [reply R/utilities.R]: Excellent! Well done for spotting that (the documentation for `cbind` is unhelpful IMO).

**Comment by briatte** [comment]
Alright, let's merge and see what happens (AppVeyor is failing for some reason that I don't understand, but Travis CI seems fine)!

File: R/utilities.R (hunk 1 above)
Comment (mcanouil) [reply R/utilities.R]: It is/was the side effect of sapply (sometimes helpful).

Here, I'm using the method cbind.data.frame to ensure a data.frame as the final results, instead of letting R guess and decide.

**Comment by mcanouil** [comment]
Appveyor is apparently failing because it cannot access some ressources it needs to initialise/install the windows virtual machine.

It should works again later.

File: R/fortify-network.R (hunk 2 above)
Comment (briatte) [reply R/fortify-network.R]: Alright!

**Comment by briatte** [comment]
Thanks a lot again. I'm in the train so not the best place to code, but I'll reorganise a few things and then edit the NEWS to make this the big change in my (weird) version history.
